name: Auto Deploy to VPS Docker

# Menentukan kapan pipeline berjalan
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Eksekusi Remote SSH ke VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22

          # Skrip yang dijalankan di dalam VPS
          script: |
            # Masuk ke folder proyek
            cd /root/modul4-compose

            # Tarik kode terbaru dari GitHub
            git pull origin main

            # Build dan jalankan container
            docker compose up -d --build

            # Bersihkan image Docker yang tidak digunakan
            docker image prune -f
